# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fcdaf3a5959849695fc6a3a6aeee99bb99fb06d9724d4e3e46f11808dc0a5685c80cb990bb07ade6cf1a2314552ca04f88b176ebb85320df46119c05d6c4189

test:
  secret_key_base: 17fae7a2143b43d38673a0e1fb4aae23afde58ce7b4b119ee12e7f25c7bb51146eb7dd328bd069134912867ed4805086529a33fdccab4ac6953db361a9ba8922

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
